# -*- coding: utf-8 -*-

language: python
python:
  - "3.5"

sudo: required
services:
  - docker

env:
  - TOXENV=unit
  - TOXENV=func

before_install:
  - docker --version
  - docker-compose --version
  - echo $DOCKER_HOST
  - docker-compose up -d

install:
  - pip install tox

script:
  - tox
