# -*- coding: utf-8 -*-

language: python
python:
  - "3.5"

sudo: required
services:
  - docker

env:
  - TOXENV=unit
  - TOXENV=func

before_install:
  - docker --version
  - docker-compose --version
  - docker-compose build
  - docker-compose up -d
  - python ./logging/provision.py

install:
  - pip install tox

script:
  - tox

after_failure:
  - docker-compose logs fluentd
  - docker-compose logs elasticsearch
  - docker-compose logs kibana

after_script:
  - docker-compose down

notifications:
  slack: smartmob-team:qwt9rBlH1lynOHkB5p7ZsyjR
