# -*- coding: utf-8 -*-

gitmesh:
  build: ./gitmesh/
  ports:
    - "8080:80"

smartmob-agent:
  build: ./smartmob-agent/
  ports:
    - "8081:80"

fileserver:
  build: ./fileserver/
  ports:
    - "8082:80"
